# Generated by Django 3.2 on 2024-05-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsuser',
            name='email',
            field=models.CharField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='lmsuser',
            name='mobile',
            field=models.BigIntegerField(blank='True', verbose_name='手机'),
        ),
    ]
