# Generated by Django 3.2 on 2024-05-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('content', models.TextField(verbose_name='notfiycontent')),
            ],
        ),
        migrations.RenameModel(
            old_name='LmsUser',
            new_name='msUser',
        ),
    ]
