# Generated by Django 3.2 on 2024-06-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20240531_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='msuser',
            name='organization',
            field=models.CharField(default='RI', max_length=32, verbose_name='RI'),
        ),
    ]
