# Generated by Django 3.2 on 2024-06-15 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_msuser_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.AddField(
            model_name='notification',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='execution_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='jdhehwevev'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='org',
            field=models.TextField(default='ICOS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
