# Generated by Django 3.2 on 2024-06-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20240616_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('message', models.TextField()),
                ('org', models.TextField()),
                ('readed', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('execution_time', models.DateTimeField()),
            ],
        ),
    ]
