# Generated by Django 3.2 on 2024-06-16 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonfile',
            name='modified_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
