# Generated by Django 3.2 on 2024-06-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_jsonfile_modified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=255)),
            ],
        ),
    ]
