# Generated by Django 3.2 on 2024-06-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_csvfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
