# Generated by Django 3.2 on 2024-06-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('organization', models.CharField(default='RI', max_length=32, verbose_name='RI')),
                ('link', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
