# Generated by Django 3.2 on 2024-06-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20240618_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
    ]
