# Generated by Django 3.2 on 2024-07-05 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_msuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('contenttype', models.CharField(max_length=32)),
                ('org', models.CharField(max_length=32)),
                ('repo', models.CharField(blank=True, max_length=32, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
