# Generated by Django 3.2 on 2024-07-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_runningtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningtask',
            name='status',
            field=models.CharField(default='waiting', max_length=32),
        ),
    ]
